services:
  postgres:
    image: postgres:17.9-alpine3.23
    container_name: challenge-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: tenpo_challenge
      POSTGRES_USER: tenpo
      POSTGRES_PASSWORD: tenpo_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenpo -d tenpo_challenge"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - challenge-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 512M

  api-mocks:
    image: wiremock/wiremock:3.9.1
    container_name: challenge-api-mocks
    restart: unless-stopped
    command: ["--port", "8080", "--global-response-templating"]
    ports:
      - "8081:8080"
    volumes:
      - ./api-mocks/wiremock:/home/wiremock
    networks:
      - challenge-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  redis:
    image: redis:7.4.2-alpine
    container_name: challenge-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - challenge-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 256M

  api-calculator:
    build:
      context: ./api-calculator
    container_name: challenge-api-calculator
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api-mocks:
        condition: service_started
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: tenpo_challenge
      DB_USERNAME: tenpo
      DB_PASSWORD: tenpo_secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PERCENTAGE_BASE_URL: http://api-mocks:8080
    ports:
      - "8080:8080"
    networks:
      - challenge-net
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 768M

volumes:
  postgres_data:
  redis_data:

networks:
  challenge-net:
    driver: bridge
